CHANNEL_MODE = 0
CHANNEL_BRIGHTNESS = 1
CHANNEL_SPEED = 2
CHANNEL_RED = 3
CHANNEL_GREEN = 4
CHANNEL_BLUE = 5

CHANNEL_SPECTRUM_MODE = 6
CHANNEL_SPECTRUM_BANDS = 7

CHANNEL_TEXT_MODE = 8
CHANNEL_TEXT_BEGIN = 32
CHANNEL_TEXT_END = 64